### ISSUE TITLE
[Bug]关于僵尸毒

### ISSUE THREAD

**Issue by sundog259** [UpKK-Xnet-YYDCS/UPKK_ZE_PUBLIC#1558]
## 简介

**玩家进入毒范围后不会立即受到伤害，能否修改受伤判定时间，在某些情况人类切刀走进毒圈会无伤逃脱**

## 重现步骤

- [x] 这个 Bug 可以稳定重现
- [ ] 这个 Bug 有时会出现
- [ ] 这个 Bug 是完全随机的
- [ ] 我不知道如何重现它

**Comment by e54385991** [comment]
在下一次插件同步中
将检测频率从1.0改为 css_poison_hurt_interval 0.3 或者更低即可 注意伤害需要调整

**Comment by e54385991** [comment]
[https://github.com/e54385991/cs2-css-Plugin/commit/9d790b8d2afd0a555ae62bdc5320179c8b33ab73](url)  #可调整毒伤害频率.

**Comment by sundog259** [comment]
还有一个问题，把毒持续时间修改比较长，特效会提前消失

**Comment by e54385991** [comment]
# 毒的特效重复播放设置 例如特效文件只能持续2秒 则可以填写为 1.5 使其提前重播
css_poison_particle_replay_interval 0.0 
https://github.com/e54385991/cs2-css-Plugin/commit/19217a1266e260322d0325c22d3e7be6c8b84dd7#diff-02cbe4911b49174c92a3033cd94164ef09162b01a2e8bd71033e3da818b8167a
