### ISSUE TITLE
添加sound

### ISSUE THREAD

**Issue by sundog259** [UpKK-Xnet-YYDCS/UPKK_ZE_PUBLIC#1575]
[ze-Grau-Extra-RTVs.zip](https://github.com/user-attachments/files/18134034/ze-Grau-Extra-RTVs.zip)

Upkk_ZE_Resource能否加两首音乐并更新soundevent，插件应该不用加。

用于ze_grau额外的RTV关卡

**Comment by e54385991** [comment]
这会是一个全局的预缓存的情况  soundevents/soundevents_ze_grau.vsndevts
cs2/counterstrikesharp/configs/plugins/UpkkWebInterfaces/ResourceFiles.txt  它至少要添加至预缓存清单才可以使用 不打算这样做

**Comment by sundog259** [comment]
> 这会是一个全局的预缓存的情况 soundevents/soundevents_ze_grau.vsndevts cs2/counterstrikesharp/configs/plugins/UpkkWebInterfaces/ResourceFiles.txt 它至少要添加至预缓存清单才可以使用 不打算为了一个地图这样做

还有个插件bug，控制台使用css_gc，输出的内容带指令

(ze_1)[大明王朝]Asteri3m: CSs_gc 来张刀剑神域

**Comment by sundog259** [comment]
!gc 不会这样

**Comment by e54385991** [comment]
CSs_gC 111 因为大小写敏感问题已修复 服务器重启后生效
https://github.com/e54385991/cs2-css-Plugin/commit/77358633f390f6048f4156167dc21b4806ad20f7#diff-6d8cd26dac12da40bea1c06f66c2267e1ea3d44f00fdf03769a00413d37b8fb3L54
